TodoListMVC/Models/ErrorViewModel.cs
namespace TodoListMVC.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

TodoListMVC/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using TodoListMVC.Models;

namespace TodoListMVC.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

TodoListMVC/Controllers/TodoListController.cs
using AutoMapper;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using TodoList.BLL.Interfaces;
using TodoList.BLL.Models;
using TodoList.DAL.Entities;

namespace TodoListMVC.Controllers
{
    [Route("[controller]/[action]/{userid?}")]
    [AutoValidateAntiforgeryToken]
    public class TodoListController : Controller
    {
        private readonly IUserService _userService;
        private readonly ITodoListService _todoService;
        private readonly IMapper _mapper;


        public TodoListController(IUserService userService, ITodoListService _todoService)
        {
            _userService = userService;
            this._todoService = _todoService;
        }

        public async Task<IActionResult> Index()
        {
            var model = await _userService.GetUsersWithTasksAsync();
            return View(model);
        }


        public async Task<IActionResult> New(int userId)
        {
            var model = await _userService.GetUser(userId);
            return View(new AddOrUpdateTaskVM { UserId = userId});
        }



        public async Task<IActionResult> UpdateStatus(int userId, int taskId)
        {
            var user = await _todoService.GetTask(userId, taskId);
            return View(user);

        }

        public IActionResult DeleteAUser(int userId)
        {
            return View(new DeleteUserVM { Id = userId });

        }



        [HttpPost]
        public async Task<IActionResult> Save(AddOrUpdateTaskVM model)
        {
            if (ModelState.IsValid)
            {

                var (successful, msg) = await _todoService.AddOrUpdateAsync(model);

                if (successful)
                {

                    TempData["SuccessMsg"] = msg;
                    return RedirectToAction("Index");
                }

                //TempData["ErrMsg"] = msg; for both views and redirect to actions
                ViewBag.ErrMsg = msg;
                return View("New");

            }
            return View("New");
        }



        [HttpPost("{taskId}")]
        public async Task<IActionResult> DeleteTask(int userId, int taskId)
        {
            if (ModelState.IsValid)
            {
                var (success, msg) = await _todoService.DeleteTaskAsync(userId, taskId);

                if (success)
                {
                    TempData["SuccessMsg"] = msg;
                    return RedirectToAction("Index");
                }

                TempData["ErrMsg"] = msg;
                return RedirectToAction("Index");
            }
            return View("Index");
        }



        [HttpGet("{taskId}")]
        public async Task<IActionResult> SaveUpdateStatus(int userId, int taskId)
        {

            if (ModelState.IsValid)
            {
                var (successful, msg) = await _todoService.ToggleTaskStatus(userId, taskId);

                if (successful)
                {
                    TempData["SuccessMsg"] = msg;
                    return RedirectToAction("Index");
                }

                TempData["ErrMsg"] = msg;
                return View("Index");

            }
            return View("Index");
        }

    }

}

TodoListMVC/Controllers/UserController.cs
using Microsoft.AspNetCore.Mvc;
using TodoList.BLL.Interfaces;
using TodoList.BLL.Models;

namespace TodoListMVC.Controllers
{
    [Route("[controller]/[action]/{id?}")]
    public class UserController : Controller
    {
        private readonly IUserService _userService;
        private readonly ITodoListService _todoService;

        public UserController(IUserService userService, ITodoListService _todoService)
        {
            _userService = userService;
            this._todoService = _todoService;
        }

        public async Task<IActionResult> NewUser(int userId)
        {
            var user = await _userService.GetUser(userId);
            return View(user);
        }


        /*public IActionResult New()
        {
            return View(new DeleteUserVM());
        }*/

        public async Task<IActionResult> UpdateUser(int userId)
        {
            var user = await _userService.GetAUser(userId);
            return View(user);
        }

        public async Task<IActionResult> AllUsers()
        {
            var model = await _userService.GetUsers();
            return View(model);
        }


        [HttpPost]
        public async Task<IActionResult> SaveUser(DeleteUserVM model)
        {

            if (ModelState.IsValid)
            {
                var (successful, msg) = await _userService.AddOrUpdateAsync(model);

                if (successful)
                {

                    TempData["SuccessMsg"] = msg;
                    return RedirectToAction("AllUsers");
                }

                // TempData["ErrMsg"] = msg; for both views and redirect to actions
                TempData["ErrMsg"] = msg;

                return View("NewUser");
            }

            return View("NewUser");

        }


        [HttpPost("{userId}")]
        public async Task<IActionResult> DeleteUser(int userId)
        {
            if (ModelState.IsValid)
            {

                var (success, msg) = await _userService.DeleteAsync(userId);
                if (success)
                {
                    TempData["SuccessMsg"] = msg;
                    return RedirectToAction("AllUsers");
                }

                TempData["ErrMsg"] = msg;
                return RedirectToAction("AllUsers");

            }
            return View("AllUsers");

        }


        [HttpPost]
        public async Task<IActionResult> SaveUpdate(UserVM model)
        {

            if (ModelState.IsValid)
            {
                var (successful, msg) = await _userService.Update(model);

                if (successful)
                {
                    TempData["SuccessMsg"] = msg;
                    return RedirectToAction("AllUsers");
                }

                TempData["ErrMsg"] = msg;
                return View("AllUsers");

            }
            return View("AllUsers");
        }

    }
}

TodoListMVC/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

TodoListMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TodoListppMVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/TodoListMVC.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">TodoListAppMVC</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>

                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="TodoList" asp-action="Index">Index</a>

                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="TodoList" asp-action="New">New Task</a>

                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="NewUser">New User</a>

                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="UpdateUser">Update Users</a>

                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="AllUsers">All Users</a>

                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - AunctionAppMVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

TodoListMVC/Views/TodoList/Index.cshtml
@model IEnumerable<TodoList.BLL.Models.UserWithTaskVM>

@if (@TempData["SuccessMsg"] != null)
{
    <div class="alert alert-success alert-dismissible fade show w-75" role="alert">
        <strong>Success!</strong> @TempData["SuccessMsg"]
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
}


@if (@TempData["ErrMsg"] != null)
{
    <div class="alert alert-danger alert-dismissible fade show w-75" role="alert">
        <strong>Error!</strong> @TempData["ErrMsg"]
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
}


@foreach (var item in Model.Select((value, i) => new { value, i }))
{
    <h4>@(item.i + 1). @item.value.Fullname's Tasks</h4>
    <h4>@item.value.Id</h4>
    <span class="px-1">
        <form action="@Url.Action("New", "TodoList", new { userId = @item.value.Id})" method="Get">
            <input type="submit" class="btn btn-success" name="_method" value="Add" placeholder="@item.value.Fullname" />
        </form>
    </span>
    <table class="table table-striped">

        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Task</th>
                <th scope="col">Description</th>
                <th scope="col">Priority</th>
                <th scope="col">Due date</th>
                <th scope="col">Status</th>
            </tr>
        </thead>
        <tbody>

            @{
                foreach (var task in item.value.Tasks.Select((value, i) => new { value, i }))
                {
                    <tr>
                        
                        <td>@task.value.Title</td>
                        <td>@task.value.Description</td>
                        <td>@task.value.Priority</td>
                        <td>@task.value.DueDate</td>
                        <td>@task.value.Status</td>
                        <td>
                            <div class="d-lg-flex">
                                <span class="px-1">                                 
                                        <form action="@Url.Action("SaveUpdateStatus", "TodoList", new { userId = @item.value.Id, taskId = @task.value.Id, _method = "Get" })">
                                        <input type="submit" class="btn btn-warning btn-rounded" value="Update"/>
                                        </form>                          
                                </span>

                             <span class="px-1">
                                <button type="button" class="btn btn-danger btn-rounded">
                                        <input href="@Url.Action("DeleteTask", "TodoList", new { userId = @item.value.Id, taskId = @task.value.Id})" value="Delete">
                                </button>
                            </span>
                            </div>
                        </td>      
                    </tr>
                }
            }
        </tbody>
    </table>

}

TodoListMVC/Views/TodoList/New.cshtml
@{
    ViewBag.Title = "title";
    Layout = "_Layout";
}
@using TodoList.DAL.Enums
@model TodoList.BLL.Models.AddOrUpdateTaskVM;


<h2>New Task</h2>


<form class="col-7" asp-controller="TodoList" asp-action="Save">

    @if (@ViewBag.ErrMsg != null)
    {
        <div class="alert alert-danger alert-dismissible fade show w-75" role="alert">
            <strong>Error!</strong> @ViewBag.ErrMsg
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
    }


    <div class="alert-danger" asp-validation-summary="@ValidationSummary.All"></div>


    <div class="mb-3">
        <input type="hidden" class="form-control" asp-for="UserId">
        <span asp-validation-for="UserId"></span>
    </div>


    <div class="mb-3">
        <input type="hidden" class="form-control" asp-for="@Model.TaskId">
        <span asp-validation-for="TaskId"></span>
    </div>


    <div class="mb-3">
        <label asp-for="@Model.Title" class="form-label"></label>
        <input class="form-control" asp-for="@Model.Title">
        <span asp-validation-for="Title" class="alert-danger"></span>
    </div>

    <div class="mb-3">
        <label asp-for="@Model.Description" class="form-label"></label>
        <textarea class="form-control" asp-for="@Model.Description"></textarea>

    </div>

    <div class="mb-3">

        <label asp-for="@Model.Priority" class="form-label"></label>
        <select class="form-select" aria-label="Default select example" asp-for="@Model.Priority" asp-items="Html.GetEnumSelectList <Priority>()">
            <option selected="" value="">Pick a Priority</option>

        </select>
    </div>

    <div class="mb-3">
        <label asp-for="@Model.DueDate" class="form-label"></label>
        <input class="form-control" asp-for="@Model.DueDate">
    </div>


    <button type="submit" class="btn btn-primary">Submit</button>
</form>

@section Scripts
    {
    @{
        Html.RenderPartial("_ValidationScriptsPartial");
    }
}

TodoListMVC/Views/User/AllUsers.cshtml
@model IEnumerable<TodoList.BLL.Models.DeleteUserVM>


@if (@TempData["SuccessMsg"] != null)
{
    <div class="alert alert-success alert-dismissible fade show" role="alert">
        <strong>Success!</strong> @TempData["SuccessMsg"]
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
}


@if (@TempData["ErrMsg"] != null)
{
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
        <strong>Error!</strong> @TempData["ErrMsg"]
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
}


    @foreach (var item in Model.Select((value, i) => new { value, i }))
    {

        <ul class="list-group">
            <li class="list-group-item d-flex justify-content-between align-items-center">

                <span>@item.value.FullName</span>
                <span>@item.value.Email</span>

                <div class="btn-group" role="group">

                    <form method="post" action="@Url.Action("DeleteUser", "User", new { userId = @item.value.Id })">
                        @Html.AntiForgeryToken()
                        <input type="submit" class="btn btn-danger" value="Delete" />
                    </form>

                    <form method="post" action="@Url.Action("UpdateUser", "User", new { userId = @item.value.Id })">
                        @Html.AntiForgeryToken()
                        <input type="submit" class="btn btn-primary" value="Update" />
                    </form>

                </div>
            </li>
        </ul>
    }


@section Scripts
    {
    @{
        Html.RenderPartial("_ValidationScriptsPartial");
    }
    ;
}

TodoListMVC/Views/User/NewUser.cshtml
@{
    ViewBag.Title = "title";
    Layout = "_Layout";
}
@model TodoList.BLL.Models.DeleteUserVM;

<h2>New User</h2>


<form class="col-7" asp-controller="User" asp-action="SaveUser">

    @if (@ViewBag.ErrMsg != null)
    {
        <div class="alert alert-danger alert-dismissible fade show w-75" role="alert">
            <strong>Error!</strong> @ViewBag.ErrMsg
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
    }

    <div class="alert-danger" asp-validation-summary="@ValidationSummary.None"></div>

    <div class="mb-3">
        <input type="hidden" asp-for="Id" />
        <span asp-validation-for="Id"></span>
    </div>

    <div class="mb-3">
        <label asp-for="@Model.FullName" class="form-label"></label>
        <input class="form-control" asp-for="@Model.FullName">
        <span asp-validation-for="FullName"></span>
    </div>


    <div class="mb-3">
        <label asp-for="@Model.Email" class="form-label"></label>
        <input class="form-control" asp-for="@Model.Email">
        <span asp-validation-for="Email"></span>
    </div>


    <div class="mb-3">
        <label asp-for="@Model.Password" class="form-label"></label>
        <input class="form-control" asp-for="@Model.Password">
        <span asp-validation-for="Password" class="alert-danger"></span>
    </div>


    <button type="submit" class="btn btn-primary">Submit</button>
</form>

@section Scripts
    {
    @{
        Html.RenderPartial("_ValidationScriptsPartial");
    }
    ;
}

TodoListMVC/Views/User/UpdateUser.cshtml
@{
    ViewBag.Title = "title";
    Layout = "_Layout";
}
@model TodoList.BLL.Models.UserVM;

<h2>Update User</h2>


<form class="col-7" asp-controller="User" asp-action="SaveUpdate">

    @if (@ViewBag.ErrMsg != null)
    {
        <div class="alert alert-danger alert-dismissible fade show" role="alert">
            <strong>Error!</strong> @ViewBag.ErrMsg
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
    }


    <div class="alert-danger" asp-validation-summary="@ValidationSummary.All"></div>

    <input type="hidden" asp-for="UserId"/>

    <div class="mb-3">
       
        <label asp-for="@Model.FullName" class="form-label"></label>
        <input class="form-control" asp-for="@Model.FullName">
        <span asp-validation-for="FullName"></span>
    </div>


    <div class="mb-3">
        
        <label asp-for="@Model.Email" class="form-label"></label>
        <input class="form-control" asp-for="@Model.Email">
        <span asp-validation-for="Email"></span>
    </div>


    @*<div class="mb-3">
        
        <label asp-for="@Model.Password" class="form-label"></label>
        <input class="form-control" asp-for="@Model.Password">
        <span asp-validation-for="Password" class="alert-danger"></span>
    </div>*@


    <button type="submit" class="btn btn-primary">Submit</button>
</form>


@section Scripts
    {
    @{
        Html.RenderPartial("_ValidationScriptsPartial");
    }
    ;
}